### ISSUE TITLE
Point new Contributors to "trivial" Issues

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum-doc#161] opened 2018-01-21 19:10 UTC
The current status of the contribution.md states:

> If you want to start contributing and not sure where to start, a good frame of reference are open GitHub issues in repositories. Issues are commonly tagged by their relevance, topic and milestone, which should provide some insight into most topical issues relevant to your expertise.

## Suggestion

The suggestion is to point potential contributors to a list of `trivial` issues (this could be a similar tag, but should be the same across exonum projects). The documentation would then be changed to something like this:

"If you want to start contributing and not sure where to start, just look at the `trivial` issues of the projects. As an example, the [exonum trivial open issues](https://github.com/exonum/exonum/issues?q=is%3Aissue+is%3Aopen+label%3Atrivial). If you are inexperienced with the work-flow, start contributing on the documentation projects."

This way both, experienced and inexperienced developers can find quickly the relevant issues.

**Comment by slowli** [comment] 2018-01-23 19:12
I think the citation from the current documentation you've provided is fine, provided there *are* trivial issues tagged as such (most of current issues are not trivial). The meaning of the tag would be quite obvious, and would not require an additional explanation, imo.

Also, could you please clarify the following sentence a little bit?

> If you are inexperienced with the work-flow, start contributing on the documentation projects.

- Does "the workflow" mean the contribution process in general, or something more specific (e.g., coding in Rust)?
- Do you mean this repo by "documentation projects," documentation in code (e.g., in the `exonum` repo), or something else entirely?

**Comment by lazaridiscom** [comment] 2018-01-23 19:37
The main point of this issue is to provide a direct link. The original text can stay as is.

>Also, could you please clarify the following sentence a little bit?
>> If you are inexperienced with the work-flow, start contributing on the documentation projects.

=> If you are inexperienced with the github work-flow, then you can start contributing on the dedicated documentation projects (like exonum/exonum-docs).

**Comment by lazaridiscom** [comment] 2018-01-23 21:33
> your suggestion stems

=> practice on documentation projects, thus you do not distract folks on code-level projects.

**Comment by lazaridiscom** [comment] 2018-01-24 23:55
@slowli, please see:

https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by slowli** [comment] 2018-01-25 13:56
Thanks for info! The problem is not that we don't know how to assign label to issues, but rather modifying the project planning and dev processes so that they would encompass external contributors by design. I believe we will eventually get there, but it may take some time.

**Comment by slowli** [comment] 2018-02-15 11:43
Closed by exonum/exonum#482, which points out the process of locating good issues.

**Closed by slowli** 2018-02-15 11:43 UTC
